(defvar +packages nil)

(defun +use-package (recipe)
  (straight-use-package recipe)
  (if (listp recipe)
      (push (car recipe) +packages)
    (push recipe +packages)))

(+use-package '(inf-iex :type git :host github :repo "DogLooksgood/inf-iex"))
(+use-package '(joker-theme :type git :host github :repo "DogLooksGood/joker-theme"))
(+use-package '(ligature :type git :host github :repo "mickeynp/ligature.el"))
(+use-package '(meow :type git :host github :repo "DogLooksGood/meow"))
(+use-package '(org-html-themify :type git :host github :repo "DogLooksGood/org-html-themify" :files ("*.el" "*.js" "*.css")))
(+use-package '(paredit :type git :host github :repo "emacsmirror/paredit"))
(+use-package '(rime :type git :host github :repo "DogLooksGood/emacs-rime"))
(+use-package '(telega :type git :host github :branch "releases"))
(+use-package 'cargo)
(+use-package 'cider)
(+use-package 'clj-refactor)
(+use-package 'clojure-mode)
(+use-package 'color-theme-sanityinc-tomorrow)
(+use-package 'company)
(+use-package 'conda)
(+use-package 'dante)
(+use-package 'dash)
(+use-package 'deadgrep)
(+use-package 'diff-hl)
(+use-package 'dired-git-info)
(+use-package 'direnv)
(+use-package 'docker)
(+use-package 'docker-compose-mode)
(+use-package 'dockerfile-mode)
(+use-package 'dot-mode)
(+use-package 'eglot)
(+use-package 'elixir-mode)
(+use-package 'emmet-mode)
(+use-package 'flycheck)
(+use-package 'flycheck-clj-kondo)
(+use-package 'flymake)
(+use-package 'gcmh)
(+use-package 'haskell-mode)
(+use-package 'htmlize)
(+use-package 'magit)
(+use-package 'markdown-mode)
(+use-package 'mix)
(+use-package 'nginx-mode)
(+use-package 'ob-restclient)
(+use-package 'org-roam)
(+use-package 'org-roam-server)
(+use-package 'org-superstar)
(+use-package 'pass)
(+use-package 'polymode)
(+use-package 'prescient)
(+use-package 'restclient)
(+use-package 'rust-mode)
(+use-package 'selectrum)
(+use-package 'selectrum-prescient)
(+use-package 'smartparens)
(+use-package 'treemacs)
(+use-package 'web-mode)
(+use-package 'yaml-mode)
(+use-package 'yascroll)
(+use-package 'yasnippet)
(+use-package 'zenburn-theme)

(provide 'init-packages)
