;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from bedit.el

(register-definition-prefixes "bedit" '("bedit-"))


;;; Generated autoloads from carbon-theme.el

(register-definition-prefixes "carbon-theme" '("carbon"))


;;; Generated autoloads from eink-theme.el

(register-definition-prefixes "eink-theme" '("eink"))


;;; Generated autoloads from minidark-theme.el

(register-definition-prefixes "minidark-theme" '("minidark"))


;;; Generated autoloads from patch-geiser.el

(register-definition-prefixes "patch-geiser" '("user/"))


;;; Generated autoloads from phosphorus-theme.el

(register-definition-prefixes "phosphorus-theme" '("phosphorus"))


;;; Generated autoloads from simple-theme.el

(register-definition-prefixes "simple-theme" '("simple"))


;;; Generated autoloads from vc6-theme.el

(register-definition-prefixes "vc6-theme" '("vc6"))



;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
